name: template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
<<<<<<< HEAD
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^6.1.1
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.6
  iconly: ^1.0.1
  image_picker: ^1.0.7
  lottie: ^2.7.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5
  url_launcher: ^6.2.3
  chewie: ^1.7.4
  another_flutter_splash_screen: ^1.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
=======
  supabase_flutter: ^2.3.4
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_sizer: ^1.0.5
  flutter_dotenv: ^5.1.0
  lottie: ^3.1.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  flutter_map: ^6.1.0
  location: ^5.0.3
  permission_handler: ^11.3.0
  provider: ^6.1.2
  collection: ^1.18.0
>>>>>>> Dat/17.03.24/init-page-welcome-login

dev_dependencies:
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true

<<<<<<< HEAD
  assets:
    - assets/lottie/
    - assets/images/
=======
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - .env
>>>>>>> Dat/17.03.24/init-page-welcome-login

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100


