on:
  pull_request:
    branches:
      - develop-nga-nguyen
name: merge_develop
jobs:
  build:
    name: Build_Test_Develop
    runs-on: windows-latest
    steps:
      - uses: action/checkout@v1
      - uses: action/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.7'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - run: |
         flutter build ios --no-codesign
         cd build/ios/iphoneos
         mkdir Payload
         cd Payload
         ln -s ../Runner.app
         cd ..
         zip -r app.ipa Payload
